/**
 * Application configuration
 */

export const CONFIG = {
  STORAGE_KEYS: {
    LANGUAGE: "bonobo-language",
    THEME: "bonobo-theme",
  },
  LANGUAGES: ["en", "el"],
  THEMES: ["light", "dark"],
  SUBCATEGORIES: {
    coffee: ["coffee", "tea", "chocolate", "juice", "soft"],
    food: [
      "breakfast",
      "salads",
      "snacks",
      "club-sandwich",
      "sandos",
      "burgers",
      "pancakes",
      "waffles",
      "fruitsalads",
      "finger-food",
      "ice-cream",
    ],
    spirits: ["gin", "vodka", "rum", "tequila", "whisky", "liqueur", "others"],
    beer: ["draft", "bottles", "craft"],
    wine: ["sparkling", "white", "rose", "red"],
    cocktails: ["signature", "classic", "mocktails"],
  },
  CATEGORIES: ["coffee", "food", "spirits", "beer", "wine", "cocktails"],
  TIME_PERIODS: {
    MORNING: {
      START: 6,
      END: 12,
      ORDER: ["coffee", "food", "wine", "beer", "cocktails", "spirits"],
    },
    LUNCH: {
      START: 12,
      END: 17,
      ORDER: ["food", "coffee", "wine", "beer", "spirits", "cocktails"],
    },
    AFTERNOON: {
      START: 17,
      END: 21,
      ORDER: ["cocktails", "coffee", "food", "beer", "wine", "spirits"],
    },
    NIGHT: {
      START: 21,
      END: 6,
      ORDER: ["cocktails", "spirits", "beer", "wine", "food", "coffee"],
    },
  },
  // Time-based food subcategory filtering
  FOOD_TIME_RESTRICTIONS: {
    // 03:00 to 17:00 - All food items available
    FULL_MENU: {
      START: 3,
      END: 17,
      ALLOWED_SUBCATEGORIES: [
        "breakfast",
        "salads",
        "snacks",
        "club-sandwich",
        "sandos",
        "burgers",
        "pancakes",
        "waffles",
        "fruitsalads",
        "finger-food",
        "ice-cream",
      ],
      ORDER: [
        "breakfast",
        "salads",
        "snacks",
        "club-sandwich",
        "sandos",
        "burgers",
        "pancakes",
        "waffles",
        "fruitsalads",
        "finger-food",
        "ice-cream",
      ],
    },
    // 17:01 to 21:00 - All except breakfast
    EVENING_MENU: {
      START: 17.01,
      END: 21,
      ALLOWED_SUBCATEGORIES: [
        "salads",
        "snacks",
        "club-sandwich",
        "sandos",
        "burgers",
        "pancakes",
        "waffles",
        "fruitsalads",
        "finger-food",
        "ice-cream",
      ],
      ORDER: [
        "salads",
        "snacks",
        "club-sandwich",
        "sandos",
        "burgers",
        "pancakes",
        "waffles",
        "fruitsalads",
        "finger-food",
        "ice-cream",
      ],
    },
    // 21:01 to 02:59 - Limited night menu with specific order
    NIGHT_MENU: {
      START: 21.01,
      END: 3,
      ALLOWED_SUBCATEGORIES: [
        "finger-food",
        "burgers",
        "sandos",
        "salads",
        "snacks",
        "club-sandwich",
        "waffles",
        "pancakes",
        "fruitsalads",
        "ice-cream",
      ],
      ORDER: [
        "finger-food",
        "burgers",
        "sandos",
        "salads",
        "snacks",
        "club-sandwich",
        "waffles",
        "pancakes",
        "fruitsalads",
        "ice-cream",
      ],
    },
  },
};
